### ISSUE TITLE
Submitting file to consumer returns 405 Method Not Allowed

### ISSUE THREAD

**Issue by mrtizmoatwork** [polyswarm/autopsy-module#8]
When submitting a file using the Right-click 'SwarmIt" option,  the file submission fails. When I try to submit the same file(s) with a curl request, I get a successful reply, although the files are tagged a 'Duplicate'.

Here is the output from the log:

```
SEVERE [io.polyswarm.swarmit.SwarmItController]: Failed to get status for submission.
org.apache.http.client.ClientProtocolException: Failed to submit file. Status code: 405, Response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
.
	at io.polyswarm.swarmit.apiclient.SwarmItApiResponseHandler.handleResponse(SwarmItApiResponseHandler.java:42)
	at io.polyswarm.swarmit.apiclient.SwarmItApiResponseHandler.handleResponse(SwarmItApiResponseHandler.java:22)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at io.polyswarm.swarmit.apiclient.SwarmItApiClient.getSubmissionStatus(SwarmItApiClient.java:103)
[catch] at io.polyswarm.swarmit.SwarmItController$ResolvePendingSubmissionsTask.run(SwarmItController.java:229)
	at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:630)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

This right-click menu posting files was working earlier today. Not sure why it isn't working now. This may not be a problem wiith the Autopsy plugin, it may be  problem with the consumer interface.

**Comment by mrtizmoatwork** [comment]
This was a bug on my part. Resolved.
